markdown: rdiscount
permalink: /:title/
url: http://ricencode.github.io
name: ricencode
author: venyao
qq: 1481758069
email: venyao@qq.com 
github: venyao
pygments: true
safe: true
paginate: 20
about: "The knowledge of cloned rice genes lost in the information of rice functional genomics studies"
